quarkus:

  # Database configuration for Docker environment
  datasource:
    db-kind: postgresql
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:your-super-secret-and-long-postgres-password}
    jdbc:
      url: ${POSTGRES_URL:jdbc:postgresql://db:5432/postgres}
      max-size: 16
    devservices:
      enabled: false

  # Updated Logging Configuration
  log:
    category:
      "org.incept5.api":
        level: DEBUG

supabase:
  jwt:
    issuer: ${SUPABASE_JWT_ISSUER:http://auth:9999}
    secret: ${SUPABASE_JWT_SECRET:your-super-secret-jwt-token-with-at-least-32-characters-long}
    realm: Incept5 API