quarkus:
  application:
    name: quarkus-api
  
  # Flyway Configuration for production and testing (@TODO move to flyway container)
  flyway:
    migrate-at-start: true
    locations: db/migration
    schemas: public, auth
    default-schema: public

  # Hibernate Configuration
  hibernate-orm:
    database:
      generation: none
    log:
      sql: true
      bind-parameters: true
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  # OpenAPI Configuration
  swagger-ui:
    always-include: true
    path: /swagger-ui

  # Dummy Database configuration to make the build pass (We use devservices in test, real DB in prod configured at docker/volumes/quarkus/application.yml)
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres
    username: changeme
    password: changeme
    devservices:
      enabled: false


