quarkus:
  application:
    name: quarkus-api
  
  # Flyway Configuration for production and testing (@TODO move to flyway container)
  flyway:
    migrate-at-start: true
    locations: db/migration
    schemas: public, auth
    default-schema: public

  # Hibernate Configuration
  hibernate-orm:
    database:
      generation: none
    log:
      sql: true
      bind-parameters: true
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  # OpenAPI Configuration
  swagger-ui:
    always-include: true
    path: /swagger-ui

  # Database configuration for Docker environment so that you can use "gradle quarkusDev" to run the app and connect to the dockerized database
  datasource:
    db-kind: postgresql
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:your-super-secret-and-long-postgres-password}
    jdbc:
      url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
      max-size: 16
    devservices:
      enabled: false

supabase:
  jwt:
    issuer: ${SUPABASE_JWT_ISSUER:http://auth:9999}
    secret: ${SUPABASE_JWT_SECRET:your-super-secret-jwt-token-with-at-least-32-characters-long}
    realm: Incept5 API
