greeting:
  message: "hello"

quarkus:
  application:
    name: quarkus-api
  
  # HTTP Configuration
  http:
    port: 8080
    cors:
      ~: true
      origins: "*"
      methods: GET,POST,PUT,DELETE,OPTIONS
      headers: Accept,Authorization,Content-Type,Origin,X-Requested-With
      exposed-headers: Content-Disposition
      access-control-max-age: 24H
  
  # Hibernate Configuration
  hibernate-orm:
    database:
      generation: none
    log:
      sql: true
      bind-parameters: true
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  
  # Development Configuration
  log:
    category:
      "org.hibernate.SQL":
        level: DEBUG
      "org.hibernate.type.descriptor.sql":
        level: DEBUG
        min-level: TRACE
  
  # OpenAPI Configuration
  swagger-ui:
    always-include: true
    path: /swagger-ui
