quarkus:
  application:
    name: quarkus-api
  
  # Flyway Configuration for production and testing (@TODO move to flyway container)
  flyway:
    migrate-at-start: true
    locations: db/migration
    schemas: public, auth
    default-schema: public

  # Hibernate Configuration
  hibernate-orm:
    database:
      generation: none
    log:
      sql: false
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  # OpenAPI Configuration
  swagger-ui:
    always-include: true
    path: /swagger-ui

  # Database configuration for Docker environment so that you can use "gradle quarkusDev" to run the app and connect to the dockerized database
  datasource:
    db-kind: postgresql
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:your-super-secret-and-long-postgres-password}
    jdbc:
      url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
      max-size: 16
    devservices:
      enabled: false

  log:
    category:
      "org.incept5.api":
        level: DEBUG
      "org.zalando.logbook":
        level: TRACE
        min-level: TRACE
      "org.hibernate":
        level: WARN 
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] (%t) %s%e%n" 

supabase:
  jwt:
    issuer: ${SUPABASE_JWT_ISSUER:http://auth:9999}
    secret: ${SUPABASE_JWT_SECRET:b3VyLWluY2VwdDUtc3VwZXItc2VjcmV0LWp3dC10b2tlbi13aXRoLWF0LWxlYXN0LTMyLWNoYXJhY3RlcnMtbG9uZw==}
    realm: Incept5 API
