quarkus:
  application:
    name: quarkus-api
  
  # HTTP Configuration
  http:
    port: 8080
    cors:
      ~: true
      origins: ${CORS_ORIGINS:*}
      methods: GET,POST,PUT,DELETE,OPTIONS
      headers: Authorization,Content-Type
      exposed-headers: Content-Disposition
      access-control-max-age: 24H
      access-control-allow-credentials: true
  
  # Hibernate Configuration
  hibernate-orm:
    database:
      generation: none
    log:
      sql: true
      bind-parameters: true
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  
  # Development Configuration
  log:
    category:
      "org.hibernate.SQL":
        level: DEBUG
      "org.hibernate.type.descriptor.sql":
        level: DEBUG
        min-level: TRACE
  
  # OpenAPI Configuration
  swagger-ui:
    always-include: true
    path: /swagger-ui

supabase:
  jwt:
    issuer: ${SUPABASE_JWT_ISSUER:https://your-project.supabase.co/auth/v1}
    secret: ${SUPABASE_JWT_SECRET:your-jwt-secret}
    realm: Incept5 API
